
use db_delivery;
insert into rol value(1,"ROLE_CLIENTE");
insert into rol value(2,"ROLE_ADMIN");
insert into rol value(3,"ROLE_CAJERO");
insert into rol value(4,"ROLE_COCINERO");
insert into rubro_articulo value(1,"Bebida");
insert into rubro_articulo value(2,"Alimento");
select * from rubro_articulo;
select * from articulo_insumo;
insert into articulo_insumo value(1,"CocaCola", 0, 70.00, 100.00, 30, 15, "ninguna", 1);
insert into articulo_insumo value(2,"pan", 1, 70.00, 100.00, 30, 15, "ninguna", 2);
select * from articulo_manufacturado;
insert into rubro_general value(1,"Bebida");
insert into rubro_general value(2, "Comida");
insert into articulo_manufacturado value(1, "Hamburguesa Comun", "/sinImagen", 200.00, 1, 2);
insert into articulo_manufacturado value(2, "Hamburguesa Especial", "/sinImagen", 250.00, 2, 2);
insert into articulo_manufacturado value(3, "Pizza Comun", "/sinImagen", 300.00, 1, 2);
select * from articulo_mfact_detalle;
insert into articulo_mfact_detalle value(1, 2, "unidad", 2, 1);
select * from usuario;